services:
  db:
    image: postgres:16
    container_name: todoapp-db
    ports:
      - 5432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
    env_file:
      - .env
    restart: on-failure
    logging:
      options:
        max-size: 10m
        max-file: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      ASPNETCORE_URLS: "http://+:80"
    depends_on:
      - db
    ports:
      - 5000:80

volumes:
  db-volume:
